language: php

php:
    - 7.1
    - 7.2
    - 7.3

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

matrix:
    include:
        - php: 7.1
          env: COMPOSER_PREFER_LOWEST=true

notifications:
    email: geloen.eric@gmail.com
